import type { Seller, Product, Review, ProductCategory } from './types';

export const sellers: Seller[] = [
  {
    id: 'seller-1',
    name: 'Edward Badiola',
    story: "With a passion for form and function, Edward transforms raw clay into timeless pieces of pottery. Each creation is a testament to minimalist design and rustic charm.",
    avatarId: 'avatar-1',
    joined: '2022-03-15',
  },
  {
    id: 'seller-2',
    name: 'Kenneth Rodriguez',
    story: "Kenneth finds beauty in reclaimed wood, giving it new life as handcrafted furniture and decor. His work celebrates the natural grain and story of the timber.",
    avatarId: 'avatar-2',
    joined: '2023-01-10',
  },
];

export const categories: ProductCategory[] = ['Pottery', 'Jewelry', 'Textiles', 'Woodwork', 'Other'];

export const products: Product[] = [
  {
    id: 'prod-1',
    name: 'Ceramic Ocean Vase',
    description: "A beautifully handcrafted ceramic vase, inspired by the deep blues of the ocean. Perfect for holding fresh flowers or as a standalone decorative piece. Each vase is unique, with slight variations in the glaze.",
    price: 85,
    imageUrls: ['https://images.unsplash.com/photo-1631125915732-b98f8774f675?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHxjZXJhbWljJTIwdmFzZXxlbnwwfHx8fDE3NjkzNDA5NTd8MA&ixlib=rb-4.1.0&q=80&w=1080', 'https://images.unsplash.com/photo-1761210719325-283557e92487?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw3fHxwb3R0ZXJ5JTIwZGV0YWlsfGVufDB8fHx8MTc2OTM0MDk1N3ww&ixlib=rb-4.1.0&q=80&w=1080'],
    sellerId: 'seller-1',
    category: 'Pottery',
    rating: 4.8,
    reviewCount: 24,
  },
  {
    id: 'prod-4',
    name: 'Hand-Carved Walnut Bowl',
    description: "A large serving bowl carved from a single piece of reclaimed walnut wood. Finished with a food-safe oil to bring out the natural beauty of the grain. Ideal for salads or as a fruit bowl.",
    price: 150,
    imageUrls: ['https://images.unsplash.com/photo-1740993384893-8163a2075022?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHx3b29kZW4lMjBib3dsfGVufDB8fHx8MTc2OTM0MDk1N3ww&ixlib=rb-4.1.0&q=80&w=1080'],
    sellerId: 'seller-2',
    category: 'Woodwork',
    rating: 4.7,
    reviewCount: 15,
  },
  {
    id: 'prod-5',
    name: 'Stoneware Mug Set',
    description: "A set of two rustic stoneware mugs, perfect for your morning coffee or tea. Features a comfortable, large handle and a speckled cream glaze.",
    price: 60,
    imageUrls: ['https://images.unsplash.com/photo-1766848482243-4379ac576b1d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw0fHxzdG9uZXdhcmUlMjBtdWdzfGVufDB8fHx8MTc2OTM0MDk1N3ww&ixlib=rb-4.1.0&q=80&w=1080'],
    sellerId: 'seller-1',
    category: 'Pottery',
    rating: 4.9,
    reviewCount: 42,
  },
  {
    id: 'prod-8',
    name: 'Live-Edge Oak Cutting Board',
    description: "A heavy-duty cutting board made from a solid slab of oak, with one side left as a natural 'live edge'. Perfect for serving charcuterie or as a durable kitchen prep surface.",
    price: 110,
    imageUrls: ['https://images.unsplash.com/photo-1628006203055-b4aa5f6300f3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwyfHxjdXR0aW5nJTIwYm9hcmR8ZW58MHx8fHwxNzY5MzQwOTU3fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    sellerId: 'seller-2',
    category: 'Woodwork',
    rating: 4.9,
    reviewCount: 19,
  },
   {
    id: 'prod-9',
    name: 'Porcelain Dinner Plate',
    description: "Elegant porcelain dinner plate with a subtle, hand-painted gold rim. The minimalist design brings a touch of sophistication to any dining table. Sold individually.",
    price: 45,
    imageUrls: ['https://images.unsplash.com/photo-1763506240757-a8a33ca2c26f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHwxMHx8cG9yY2VsYWluJTIwcGxhdGV8ZW58MHx8fHwxNzY5MzQwOTU3fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    sellerId: 'seller-1',
    category: 'Pottery',
    rating: 4.7,
    reviewCount: 30,
  },
  {
    id: 'prod-12',
    name: 'Cherry Wood Coasters',
    description: "A set of four coasters handcrafted from rich cherry wood. Each coaster is polished to a smooth finish and has a unique grain pattern.",
    price: 55,
    imageUrls: ['https://images.unsplash.com/photo-1611841528417-6227ffbca5ee?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3NDE5ODJ8MHwxfHNlYXJjaHw2fHx3b29kJTIwY29hc3RlcnN8ZW58MHx8fHwxNzY5MzQwOTU3fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    sellerId: 'seller-2',
    category: 'Woodwork',
    rating: 4.9,
    reviewCount: 33,
  },
];

export const reviews: Review[] = [
  {
    id: 'rev-1',
    productId: 'prod-1',
    author: 'Sarah L.',
    rating: 5,
    title: 'Absolutely stunning!',
    comment: "The vase is even more beautiful in person. The glaze is incredible and it was packaged so carefully. A true piece of art.",
    date: '2023-10-02',
  },
  {
    id: 'rev-2',
    productId: 'prod-1',
    author: 'David Chen',
    rating: 5,
    title: 'Perfect centerpiece',
    comment: "This vase has become the focal point of my dining room. You can feel the quality and care that went into making it. Highly recommend.",
    date: '2023-09-15',
  },
  {
    id: 'rev-3',
    productId: 'prod-1',
    author: 'Maria Garcia',
    rating: 4,
    title: 'Beautiful, but smaller than expected',
    comment: "A lovely vase, though I imagined it would be a bit larger based on the photos. The craftsmanship is undeniable, however.",
    date: '2023-08-21',
  },
    {
    id: 'rev-6',
    productId: 'prod-5',
    author: 'Ben Carter',
    rating: 5,
    title: 'My new favorite mugs',
    comment: "These mugs feel so good to hold. They have a wonderful weight to them and keep my coffee hot. They are my new daily drivers.",
    date: '2023-12-01',
  },
  {
    id: 'rev-7',
    productId: 'prod-5',
    author: 'Isabella Rossi',
    rating: 5,
    title: 'Charming and rustic',
    comment: "I love the rustic look of these mugs. They bring a cozy, cafe feel to my kitchen. The quality is fantastic.",
    date: '2023-11-18',
  },
];
