import type { Seller, Product, Review, ProductCategory } from './types';

export const sellers: Seller[] = [
  {
    id: 'seller-1',
    name: 'Elena Vance',
    story: "From a young age, I was fascinated by the way clay could be transformed. I spent years honing my craft in a small studio overlooking the sea, and now I bring my creations to you. Each piece is an echo of the tides and the tranquil coastal life.",
    avatarId: 'avatar-1',
    joined: '2021-06-15',
  },
  {
    id: 'seller-2',
    name: 'Marcus Thorne',
    story: "I believe that the spirit of the forest lives in the wood I work with. My process is slow and deliberate, honoring the natural grain and form of each piece of timber. My goal is to create items that bring a piece of the wild into your home.",
    avatarId: 'avatar-2',
    joined: '2022-01-20',
  },
  {
    id: 'seller-3',
    name: 'Anya Petrova',
    story: "My grandmother taught me the art of weaving, a tradition passed down through generations in my family. I use natural dyes and traditional patterns to create textiles that are both timeless and modern, each thread telling a part of our story.",
    avatarId: 'avatar-3',
    joined: '2022-09-01',
  },
    {
    id: 'seller-4',
    name: 'Kenji Tanaka',
    story: "My work is a conversation between metal and stone. I travel to find unique gems and draw inspiration from ancient jewelry-making techniques to create pieces that feel both powerful and personal. Each design is a small sculpture to be worn.",
    avatarId: 'avatar-4',
    joined: '2023-03-10',
  },
];

export const categories: ProductCategory[] = ['Pottery', 'Jewelry', 'Textiles', 'Woodwork', 'Other'];

export const products: Product[] = [
  {
    id: 'prod-1',
    name: 'Ceramic Ocean Vase',
    description: "A beautifully handcrafted ceramic vase, inspired by the deep blues of the ocean. Perfect for holding fresh flowers or as a standalone decorative piece. Each vase is unique, with slight variations in the glaze.",
    price: 85,
    imageIds: ['prod-1-1', 'prod-1-2'],
    sellerId: 'seller-1',
    category: 'Pottery',
    rating: 4.8,
    reviewCount: 24,
  },
  {
    id: 'prod-2',
    name: 'Silver Moon Locket',
    description: "A delicate sterling silver locket with a crescent moon engraving. It opens to hold two small photos. Comes with a fine silver chain.",
    price: 120,
    imageIds: ['prod-2-1'],
    sellerId: 'seller-4',
    category: 'Jewelry',
    rating: 4.9,
    reviewCount: 31,
  },
  {
    id: 'prod-3',
    name: 'Sunset Weaver Blanket',
    description: "A soft, warm blanket woven from 100% merino wool. The colors are inspired by a sunset, with shades of orange, pink, and purple. Hand-dyed and woven on a traditional loom.",
    price: 250,
    imageIds: ['prod-3-1'],
    sellerId: 'seller-3',
    category: 'Textiles',
    rating: 5,
    reviewCount: 18,
  },
  {
    id: 'prod-4',
    name: 'Hand-Carved Walnut Bowl',
    description: "A large serving bowl carved from a single piece of reclaimed walnut wood. Finished with a food-safe oil to bring out the natural beauty of the grain. Ideal for salads or as a fruit bowl.",
    price: 150,
    imageIds: ['prod-4-1'],
    sellerId: 'seller-2',
    category: 'Woodwork',
    rating: 4.7,
    reviewCount: 15,
  },
  {
    id: 'prod-5',
    name: 'Stoneware Mug Set',
    description: "A set of two rustic stoneware mugs, perfect for your morning coffee or tea. Features a comfortable, large handle and a speckled cream glaze.",
    price: 60,
    imageIds: ['prod-5-1'],
    sellerId: 'seller-1',
    category: 'Pottery',
    rating: 4.9,
    reviewCount: 42,
  },
  {
    id: 'prod-6',
    name: 'Turquoise River Ring',
    description: "A statement ring featuring a striking piece of natural turquoise set in hammered sterling silver. The design mimics the flow of a river around a stone.",
    price: 180,
    imageIds: ['prod-6-1'],
    sellerId: 'seller-4',
    category: 'Jewelry',
    rating: 4.8,
    reviewCount: 22,
  },
  {
    id: 'prod-7',
    name: 'Botanical-Dyed Linen Scarf',
    description: "A lightweight and breathable linen scarf, naturally dyed with eucalyptus leaves to create a unique, earthy pattern. Soft to the touch and perfect for all seasons.",
    price: 75,
    imageIds: ['prod-7-1'],
    sellerId: 'seller-3',
    category: 'Textiles',
    rating: 5,
    reviewCount: 12,
  },
  {
    id: 'prod-8',
    name: 'Live-Edge Oak Cutting Board',
    description: "A heavy-duty cutting board made from a solid slab of oak, with one side left as a natural 'live edge'. Perfect for serving charcuterie or as a durable kitchen prep surface.",
    price: 110,
    imageIds: ['prod-8-1'],
    sellerId: 'seller-2',
    category: 'Woodwork',
    rating: 4.9,
    reviewCount: 19,
  },
   {
    id: 'prod-9',
    name: 'Porcelain Dinner Plate',
    description: "Elegant porcelain dinner plate with a subtle, hand-painted gold rim. The minimalist design brings a touch of sophistication to any dining table. Sold individually.",
    price: 45,
    imageIds: ['prod-9-1'],
    sellerId: 'seller-1',
    category: 'Pottery',
    rating: 4.7,
    reviewCount: 30,
  },
  {
    id: 'prod-10',
    name: 'Gold Leaf Earrings',
    description: "Delicate earrings made from 18k gold-plated brass, shaped like ginkgo leaves. Lightweight and elegant for everyday wear or special occasions.",
    price: 95,
    imageIds: ['prod-10-1'],
    sellerId: 'seller-4',
    category: 'Jewelry',
    rating: 4.8,
    reviewCount: 25,
  },
  {
    id: 'prod-11',
    name: 'Hand-Dyed Silk Pillow',
    description: "A luxurious silk pillow cover, hand-dyed using the shibori technique to create a beautiful indigo pattern. Adds a touch of artisanal elegance to any room. Cover only.",
    price: 130,
    imageIds: ['prod-11-1'],
    sellerId: 'seller-3',
    category: 'Textiles',
    rating: 5,
    reviewCount: 14,
  },
  {
    id: 'prod-12',
    name: 'Cherry Wood Coasters',
    description: "A set of four coasters handcrafted from rich cherry wood. Each coaster is polished to a smooth finish and has a unique grain pattern.",
    price: 55,
    imageIds: ['prod-12-1'],
    sellerId: 'seller-2',
    category: 'Woodwork',
    rating: 4.9,
    reviewCount: 33,
  },
];

export const reviews: Review[] = [
  {
    id: 'rev-1',
    productId: 'prod-1',
    author: 'Sarah L.',
    rating: 5,
    title: 'Absolutely stunning!',
    comment: "The vase is even more beautiful in person. The glaze is incredible and it was packaged so carefully. A true piece of art.",
    date: '2023-10-02',
  },
  {
    id: 'rev-2',
    productId: 'prod-1',
    author: 'David Chen',
    rating: 5,
    title: 'Perfect centerpiece',
    comment: "This vase has become the focal point of my dining room. You can feel the quality and care that went into making it. Highly recommend.",
    date: '2023-09-15',
  },
  {
    id: 'rev-3',
    productId: 'prod-1',
    author: 'Maria Garcia',
    rating: 4,
    title: 'Beautiful, but smaller than expected',
    comment: "A lovely vase, though I imagined it would be a bit larger based on the photos. The craftsmanship is undeniable, however.",
    date: '2023-08-21',
  },
  {
    id: 'rev-4',
    productId: 'prod-3',
    author: 'James Smith',
    rating: 5,
    title: 'Worth every penny',
    comment: "This blanket is the coziest thing I've ever owned. The colors are so vibrant and it's incredibly soft. A true heirloom piece.",
    date: '2023-11-05',
  },
  {
    id: 'rev-5',
    productId: 'prod-3',
    author: 'Chloe Kim',
    rating: 5,
    title: 'A work of art',
    comment: "I have this draped over my sofa and it's just stunning. It's too beautiful to even use! The quality is exceptional.",
    date: '2023-10-22',
  },
    {
    id: 'rev-6',
    productId: 'prod-5',
    author: 'Ben Carter',
    rating: 5,
    title: 'My new favorite mugs',
    comment: "These mugs feel so good to hold. They have a wonderful weight to them and keep my coffee hot. They are my new daily drivers.",
    date: '2023-12-01',
  },
  {
    id: 'rev-7',
    productId: 'prod-5',
    author: 'Isabella Rossi',
    rating: 5,
    title: 'Charming and rustic',
    comment: "I love the rustic look of these mugs. They bring a cozy, cafe feel to my kitchen. The quality is fantastic.",
    date: '2023-11-18',
  },
];
